name: Build Android ARM64 Addon

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/linuxserver/docker-kodi-android

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Patch guide URL
        run: |
          sed -i 's~https://my.hdhomerun.com~https://api.hdhomerun.com~g' src/HDHomeRunTuners.cpp

      - name: Build addon
        run: |
          ./bootstrap
          ./configure -q --prefix=/out
          make -j$(nproc)
          make zip ADDON_SRC_PREFIX=.

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pvr.hdhomerun-android-arm64
          path: ./pvr.hdhomerun-*.zip
